name: "📚 Blog Updater"

on:
  workflow_dispatch:
  schedule:
    - cron: '0 */12 * * *'

jobs:
  update_blogs:
    name: "Update Blogs"
    runs-on: ubuntu-latest
    steps:
      - name: "📥  Fetching Repository Contents"
        uses: actions/checkout@main

      - name: "📚  Hashnode Updater"
        uses: "varunsridharan/action-hashnode-blog@1.1.1"
        with:
          USERNAME: 'programmingfire' # Hashnode Username
          COUNT: 5 # MAX Visisble
          STYLE: "blog-alternate"
          BLOG_URL: "https://programmingfire.com"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
